# Generated by Django 5.1.3 on 2024-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familya', models.CharField(max_length=250)),
                ('yosh', models.IntegerField()),
                ('coinlar', models.IntegerField()),
                ('xp_level', models.IntegerField()),
                ('rasm', models.ImageField(upload_to='rasmlar/')),
            ],
        ),
    ]
